### ISSUE TITLE
how can I help this idea

### ISSUE THREAD

**Issue by GiovanniSM20** [pp-project/pp-project.github.io#1]
I found the idea very interesting, how could I help ?

**Comment by GiovanniSM20** [comment]
I would like to send a PR with a simple structure for PWA using preact or polymer...

**Comment by anabastos** [comment]
@GiovanniSM20 Nice! It would be very helpfull!
Till now we were considering develop the landing page using vue or react but thinking about it, I guess preact would great 😸 
Also, PWA sure it's a great choice since people usually listen to podcasts when they are on the commute or en route to anywhere so the 3g connection may be a problem.
What do you think @Halfeld?

**Comment by Halfeld** [comment]
@anabastos @GiovanniSM20 Hmm ... I disregarded those flavors of React, even more after the release of version 0.15, for reasons of [this](https://reactjs.org/blog/2016/04/07/react-v15.html).
And as the idea is not only to be a landing page but rather a wrapper of the episodes that are in the soundcloud, we will do in Vue by the productivity :D

What do you think @anabastos @GiovanniSM20 ?

**Comment by GiovanniSM20** [comment]
sure @Halfeld you can share some piece of layout with us or you prefer let's start and then help ?

and I did not quite understand what he meant by "we will do in Vue by the productivity"

but I also like Vue.js... :octocat:

**Comment by Halfeld** [comment]
Check out README :D

**Comment by Halfeld** [comment]
The first episode will come out this weekend without PWA, only with soundcloud and itunes.
Finishing editing 45min audio xD

**Comment by Halfeld** [comment]
First ep: https://soundcloud.com/user-663337641/concorrencia-elixir-ou-go
